### ISSUE TITLE
List all accounts in the service

### ISSUE THREAD

**Issue by elabbk** [elabbk/devops-capstone-project#6]
**As a** [role]  
**I need** [function]  
**So that** [benefit]  
      
### Details and Assumptions
    * [document what you know]      

### Acceptance Criteria     
    gherkin 
    Given [some context]
    When [certain action is taken]
    Then [the outcome of action is observed]

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added the list_accounts function to handle GET requests for all accounts. Updated the test file to include a test case for listing accounts.

You can review changes in this commit: https://github.com/mnmnk43434/elabbk-devops-capstone-project-8/commit/6e8845a3e126a34ab601660b987094afdd33d9f6.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
